import Uniq from './uniq.core';
import empty from './uniq.empty';
import of from './uniq.of';
import isEmpty from './uniq.isEmpty';
import exists from './uniq.exists';
import filter from './uniq.filter';
import map from './uniq.map';
import fold from './uniq.fold';
import foldRight from './uniq.foldRight';
import every from './uniq.every';
import partition from './uniq.partition';
import toArray from './uniq.toArray';
import toVec from './uniq.toVec';
import toMap from './uniq.toMap';
import toDict from './uniq.toDict';
import difference from './uniq.difference';
import intersect from './uniq.intersect';
import isProperSupersetOf from './uniq.isProperSupersetOf';
import isProperSubsetOf from './uniq.isProperSubsetOf';
import isSubsetOf from './uniq.subsetOf';
import isSupersetOf from './uniq.isSupersetOf';
import union from './uniq.union';

Uniq.empty = empty;
Uniq.of = of;

Uniq.prototype.isEmpty = isEmpty;
Uniq.prototype.exists = exists;
Uniq.prototype.filter = filter;
Uniq.prototype.map = map;
Uniq.prototype.fold = fold;
Uniq.prototype.foldRight = foldRight;
Uniq.prototype.every = every;
Uniq.prototype.partition = partition;
Uniq.prototype.toArray = toArray;
Uniq.prototype.toVec = toVec;
Uniq.prototype.toMap = toMap;
Uniq.prototype.toDict = toDict;
Uniq.prototype.difference = difference;
Uniq.prototype.intersect = intersect;
Uniq.prototype.isProperSubsetOf = isProperSubsetOf;
Uniq.prototype.isProperSupersetOf = isProperSupersetOf;
Uniq.prototype.isSubsetOf = isSubsetOf;
Uniq.prototype.isSupersetOf = isSupersetOf;
Uniq.prototype.union = union;

export default Uniq;
